### PR TITLE
[6.0] Adding filter to remove unwanted empty arrays and avoid exceptions

### PR DESCRIPTION
**Pull request by m2de**
This fixes issue #316 by removing empty values/arrays from the filters and the search performs as expected.

### CODE REVIEW

**Comment by nunomaduro** [comment]
@m2de What happens if a filter contains the value `0` or `false`?

**Comment by m2de** [comment]
Hey @nunomaduro . Fair point. Could I filter to remove any array values if only string values are supported? Happy to amend code if that would be an acceptable solution. I'm unable to resolve the issue outside of this package.

**Comment by m2de** [comment]
Thanks for your help all. Was my bad after all!

**Comment by taylorotwell** [comment]
Sounds like something that may need tests.

**Pull request closed without merging**
