### PR TITLE
Any plan to support Lumen?

### PR DESCRIPTION
**Pull request by appkr**
The box content was not working under a Lumen project. I manage to make it work, so I'd like to share it with others. Thanks.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you explain why it doesn't work under Lumen in the first place?

**Comment by appkr** [comment]
@taylorotwell `config_path()` helper was not available in Lumen. I think that was the root cause.

```sh
~/lumen-product $ php artisan
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined function Laravel\Scout\config_path()
```

**Comment by taylorotwell** [comment]
I still don't want to run these commands if the application is not in console mode.

**Comment by taylorotwell** [comment]
I don't really like this change to be honest. I don't like specificially detecting Lumen in the code like that.

**Comment by appkr** [comment]
Ok then, how about adding the `config_path()` helper on Lumen framework? There was no way for Lumen users to make the scout work without that helper. Thanks~

**Comment by appkr** [comment]
Let me post this for others who are researching on how to use scout in lumen project. The right solution was...

```php
// bootstrap/app.php

$app->register(Laravel\Scout\ScoutServiceProvider::class);
$app->configure('scout');
```

That's it.

**Comment by RudyJessop** [comment]
This solution would work great in scenarios where you would need a laravel/external package, lumen is a mico-framework. Its meant to be lightweight initially.

**Pull request closed without merging**
