### PR TITLE
Fixing issue 825

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
Fixing an issue caused import command or any other process that deals with the collection to recreate the collection as the exists flags wasn't updated properly.

[Related Issue](https://github.com/laravel/scout/issues/825)
[Other Related Issue](https://github.com/laravel/scout/issues/818)
[Previous PR](https://github.com/laravel/scout/pull/820)

### CODE REVIEW

**Comment by driesvints** [comment]
I'd give much more detailed info here for Taylor to review. Otherwise it won't be clear why this is needed.

**Comment by taylorotwell** [comment]
But now the method says it returns a Collection in the docblock but actually returns an index?

**Comment by AbdullahFaqeir** [comment]
> But now the method says it returns a Collection in the docblock but actually returns an index?

I apologise as this is a mess-naming for the variable, will make sure to fix this.

**Comment by stammbach** [comment]
Hey there, I would really appreciate this getting in asap. The latest version makes Scout + Typesense unusable with "large" datasets over 500 items. First time trying Scout & this makes onboarding really hard.

The previous version or applying this fix works as expected.

**Comment by driesvints** [comment]
@stammbach feel free to send in another PR that we can merge in faster.

**Comment by stammbach** [comment]
@driesvints I've included the fix in one of my PRs becuase I touched that line anyway. Not sure if this makes anything faster but would really appreciate you checking it out.

**Comment by AbdullahFaqeir** [comment]
@taylorotwell I apologise for taking too long to fix this, I've committed a fix to the variable name.

**Comment by driesvints** [comment]
@AbdullahFaqeir Taylor doesn't sees draft PR's. Please mark this as ready if you need another review.

**Pull request merged**
