### PR TITLE
[8.0] Rename and change queueMakeSearchable and queueRemoveFromSearch. Add RemoveFromSearch job

### PR DESCRIPTION
**Pull request by matchish**
queueMakeSearchable has code duplication with MakeSearchable job
queueMakeSearchable must not return value as it declared as void
queueRemoveFromSearch and queueMakeSearchable renamed because it dispatches job but doesn't push it to queue if scout.queue is false
I can't write tests for the methods because package don't have 'config' 'dispatch' and 'dispatch_now' helpers so I should change signatures of  queueMakeSearchable and queueRemoveFromSearch methods and pass dependencies as arguments
Added RemoveFromSearch job
ifEmpty check on collection removed because of it duplicated in MakeSearchable and RemoveFromSearch jobs

### CODE REVIEW

**Comment by driesvints** [comment]
Eh, I'm not so sure if all these changes are necessary...

**Comment by matchish** [comment]
I agree that it works without these changes)
But it's hard to test without these changes(dirty tricks requires)
If you open SearchableTest you can see that we don't have tests wich cover dispatching MakeSearchable job
But we have a dirty trick with config function(overided in the test)
Also queueFromSearch delete records from search immediately, not in queue

**Comment by matchish** [comment]
Now have more tests. And these test less fragile because don't rely on implementation details

**Comment by taylorotwell** [comment]
Thanks for your pull request to Laravel!

Unfortunately, I'm going to delay merging this code for now. To preserve our ability to adequately maintain the framework, we need to be very careful regarding the amount of code we include. 

If possible, please consider releasing your code as a package so that the community can still take advantage of your contributions! 

If you feel absolutely certain that this code corrects a bug in the framework, please "**@**" mention me in a follow-up comment with further explanation so that GitHub will send me a notification of your response.

**Comment by matchish** [comment]
@taylorotwell Thanks for reply. No, problem, I understand.
What about this line? https://github.com/laravel/scout/blob/484ff556fe2def2eab9f8eb2e60becba36c439d9/src/Searchable.php#L83
Should we introduce RemoveFromSearch job?

**Comment by jshayes** [comment]
It used to be like that, it seems like it was intentionally deleted at some point.
https://github.com/laravel/scout/commit/f46b2b8a343162cf227afeb2dcd3709cb4bc626b

Also, it seems like there would be an issue when queueing up deletes, when the object is deleted by the time the job runs. The serializes models trait won't be able to unserialize the models since they no longer exist.

**Pull request closed without merging**
