### PR TITLE
Restrict indexing of a model

### PR DESCRIPTION
**Pull request by dchristophersen**
This pr is fixing #42.

The engines `update` method will look for an `indexOnly` method on the model. If this method is present the model will only be indexed when `indexOnly` returns `true`

### CODE REVIEW

**Comment by taylorotwell** [comment]
This could be implemented by just having searchableAs return an empty array.

**Comment by dennisoderwald** [comment]
@taylorotwell This does not solve the issue. Scout create a record only with a `objectID`. But that does not make sense, since it unnecessarily consumes storage.

**Comment by taylorotwell** [comment]
No I’m saying you should submit a PR that doesn’t index the object if you return an empty array. I wasn’t saying it works that way now.

**Comment by dennisoderwald** [comment]
Ah @taylorotwell, misunderstanding. :D I talk with @dchristophersen and we submit a new PR, when it's ready.

**Pull request closed without merging**
