### PR TITLE
[9.x] Meilisearch index command

### PR DESCRIPTION
**Pull request by driesvints**
Ports over the `IndexCommand` from Meilisearch which is pretty handy for managing your indexes. I've also implemented a generic way so it works for all engines.

### CODE REVIEW

**Comment by driesvints** [comment]
I'll make this generic so it can be added into any engine really.

**Comment by mmachatschek** [comment]
We have unit tests that could be added too. https://github.com/meilisearch/meilisearch-laravel-scout/blob/main/tests/Unit/MeilisearchConsoleCommandTest.php

**Comment by taylorotwell** [comment]
I split this into `scout:index` and `scout:delete-index`.

**Comment by driesvints** [comment]
@mmachatschek can you PR that?

**Pull request merged**
