### PR TITLE
Removed numericFilters from AlgoliaEngine.

### PR DESCRIPTION
**Pull request by Boorinio**
Hopefully fixes 
https://github.com/laravel/scout/issues/831
@driesvints

### CODE REVIEW

**Comment by taylorotwell** [comment]
The docs say `where` is for numeric equality checks.

**Comment by Boorinio** [comment]
> The docs say `where` is for numeric equality checks.

Indeed, which is inconsistent with how meilisearch works (which supports everything). The docs also mention this
```
$orders = Order::search('Star Trek')->whereIn(
    'status', ['open', 'paid']
)->get();

```
Which currently doesn't work

**Comment by driesvints** [comment]
@taylorotwell there is indeed a deeper underlying issue here with inconsistency between drivers. I feel like we have an opportunity here to align the different drivers more and at the same time make the Algolia search more powerful. Could we reconsider?

**Comment by taylorotwell** [comment]
I guess we'll give it a shot. Will have to roll it back if it breaks something.

**Comment by taylorotwell** [comment]
@driesvints we need to test this on a real Laravel application before it can be released.

**Comment by Boorinio** [comment]
> I guess we'll give it a shot. Will have to roll it back if it breaks something.

Thanks for merging this, if it does break something you can comment here, I will be happy to do a follow up!

**Comment by driesvints** [comment]
@Boorinio unfortunately we had to revert this one as it's incompatible with https://github.com/algolia/scout-extended which still expects numericFilters. Can you re-attempt the PR to 11.x and also add an entry to the upgrade guide?

**Pull request merged**
