### PR TITLE
Added Elasticsearch engine

### PR DESCRIPTION
**Pull request by ErickTamayo**
Added Elasticsearch engine.

Somehow the test `test_map_correctly_maps_results_to_models` is failing because a weird interaction with the collection `->keyBy` method. The `AlgoliaEngineTest` is failing at the same point, I've tested it on a real elastic search installation and the mapping works fine. Will check tomorrow what's going on with that.

The updates and deletes are done in bulk to prevent to go each time to ES for multiple models.

### CODE REVIEW

**Comment by taylorotwell** [comment]
We already have a PR open for this. Can you contribute there?

**Comment by ErickTamayo** [comment]
@taylorotwell Just saw it, the implementation is a bit different, should I wait for merge, then change?

**Comment by hernandev** [comment]
@ErickTamayo i can give access on the repo so you can commit on the PR directly

**Comment by ErickTamayo** [comment]
@hernandev sure! can you take a look about this implementation and give any thoughts?

**Comment by hernandev** [comment]
The main difference looks like filtering options, gonna clone to test locally here and try to compare performance, looks like both are functional, liked the tests, since i haven't done them there

**Comment by ErickTamayo** [comment]
@hernandev alright, LMK so I can contribute on your PR, is @taylorotwell accepting PRs for engine drivers? I saw in Laravel News to make drivers as packages instead of PRs directly to this repo.

https://laravel-news.com/2016/08/laravel-scout-is-now-open-for-developer-testing/?utm_medium=feed&utm_source=twitter.com&utm_campaign=Feed%3A+laravelnews

**Comment by hernandev** [comment]
@ErickTamayo added you, please send changes on develop first so we can review and merge on master so it will appears on the PR

**Pull request closed without merging**
