### PR TITLE
Update ScoutServiceProvider.php

### PR DESCRIPTION
**Pull request by siddiquiazam**
Include variable $meilisearchClientClassName inside closure.

### CODE REVIEW

**Comment by mohamed-foly** [comment]
Same issue with me
Message: Undefined variable $meilisearchClientClassName
Path: vendor/laravel/scout/src/ScoutServiceProvider.php:46

@taylorotwell 
@driesvints 
It's a blocking issue needs a merge as soon as possible

**Comment by alignwebs** [comment]
Please merge it asap!

**Comment by driesvints** [comment]
Heya, sorry I sent a PR in myself with a test to make sure we catch this in the future. Thanks!

**Comment by siddiquiazam** [comment]
@driesvints Thanks for the new test, because of this issue I was not able to merge on production.

**Pull request closed without merging**
