### PR TITLE
[9.x] Support MeiliSearch Engine

### PR DESCRIPTION
**Pull request by mmachatschek**
Integration suggestion discussed in #454

### CODE REVIEW

**Comment by taylorotwell** [comment]
Any thoughts on this comment? https://github.com/laravel/scout/issues/454#issuecomment-811041907

**Comment by mmachatschek** [comment]
@driesvints still need to add the lazy collection functionallity, will update the PR tomorrow morning

**Comment by driesvints** [comment]
@mmachatschek cleaned up the PR a bit. The lgtm overall. Make sure to thoroughly test it as well in a real app with a real Meilisearch connection.

**Comment by mmachatschek** [comment]
@driesvints I just tested this out with your changes as well, here a screenshot
image

**Comment by taylorotwell** [comment]
Thanks for your work on this all!

**Pull request merged**
