### PR TITLE
Pagination simplification

### PR DESCRIPTION
**Pull request by jmarcher**
As the local variable is used only one time

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why did you change the calculation?

**Comment by jmarcher** [comment]
I mean why use the same variable two times in the same line?

    (A * B) - B = (1 - A) * B

maybe is just a mater of taste but I find the right side better

**Comment by taylorotwell** [comment]
Please use the same calculation.

**Comment by jmarcher** [comment]
done

**Pull request merged**
