### PR TITLE
Add numeric facet filters

### PR DESCRIPTION
**Pull request by dorin-niscu**

### CODE REVIEW

**Comment by morloderex** [comment]
What does excatly does this do?

**Comment by dorin-niscu** [comment]
In the current version we can only apply numeric filters: $orders = App\Order::search('Star Trek')->where('user_id', 1)->get();

I created two methods for numeric / facet filters so we can also use algolia facet filters:
$orders = App\Order::search('Star Trek')->where('locale', 'en')->get();

**Comment by taylorotwell** [comment]
You can use new macroable feature to add this. I plan to keep core very simple.

**Comment by dorin-niscu** [comment]
I understand.
Can you please provide us an example?
Thank you.

**Comment by dorin-niscu** [comment]
I found a better way to apply facet filters using the search callback.
```
$orders = App\Order::search('Star Trek', function ($algolia, $query, $options) {
            $options = array_merge($options, [
                'facetFilters' => ['locale:en']
            ]);
            return $algolia->search($query, $options);
        })->get();
```

**Pull request closed without merging**
