### PR TITLE
Added the ability to pass an array of options to full-text search.

### PR DESCRIPTION
**Pull request by den1n**
Extended example from Scout docs.

```php
use Laravel\Scout\Attributes\SearchUsingFullText;
use Laravel\Scout\Attributes\SearchUsingPrefix;
 
/**
 * Get the indexable data array for the model.
 *
 * @return array
 */
#[SearchUsingPrefix(['id', 'email'])]
#[SearchUsingFullText(['bio'])]
#[SearchUsingOptions(['mode' => 'websearch', 'language' => 'german'])]
public function toSearchableArray()
{
    return [
        'id' => $this->id,
        'name' => $this->name,
        'email' => $this->email,
        'bio' => $this->bio,
    ];
}
```

### CODE REVIEW

**Review by driesvints — APPROVED** [review]

**Comment by taylorotwell** [comment]
Could we just pass the options as a second argument to the `SearchUsingFullText` attribute? Mark as ready for review when you are ready for me to take a look again.

**Comment by taylorotwell** [comment]
Could we just pass the options as a second argument to the `SearchUsingFullText` attribute? Mark as ready for review when you are ready for me to take a look again.

**Comment by den1n** [comment]
> Could we just pass the options as a second argument to the `SearchUsingFullText` attribute?
Done.

**Comment by phuclh** [comment]
I got this error after updating to this version
CleanShot 2022-04-04 at 23 56 59@2x
n

The element with key index 1 doesn't exist
CleanShot 2022-04-04 at 23 59 47@2x

This is how I defined the `SearchUsingFullText` attribute:

CleanShot 2022-04-05 at 00 00 20@2x

**Pull request merged**
